[project]
name = "pipelinespec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.5.0",
    "mitmproxy>=12.2.3",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "singleton-decorator>=1.0.0",
]

[project.scripts]
sample = "pipelinespec.cli.sample:main"
pipelinespec = "pipelinespec.cli.main:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
